---
title: "Forecasting the 2021 Canadian Election with MRP"
description: |
  Supported by the Canadian Election Study and TODO
output:
  distill::distill_article:
    toc: true
    toc_depth: 3  
---

## Overview

The 2021 Canadian Election will be held on 20 September. Multilevel regression with post-stratification (MRP) is one way to forecast an election. It trains a model on a survey, and then applies that trained model to another dataset. It can be used to generate estimates for all 338 ridings, however the tradeoff is increased uncertainty. 

The Canadian Election Study - http://www.ces-eec.ca - is partnering with TODO to provide students with an opportunity to use MRP to forecast the 2021 Canadian election.

This page contains links to code and data that you need to get started. How you go further with this is up to you. We are providing simulated survey data that you should use to when deciding on your model. 

Please register your interest by filling out this form: : TODO ADD LINK.

We recommend working as part of a team. Develop your model and then push it to a GitHub. Register your final model with us. Before the polls close, you should commit the final version of your model to GitHub. After the polls close, we will provide the real dataset so that you can evaluate how your model did.

The three teams that have the most accurate forecast will be invited to present their work at a special meeting of the Toronto Data Workshop to be held in early October.



## Data

### Survey data

TODO: Add code and simulated data.

### Post-stratification data

TODO: Add cleaned up version of https://www12.statcan.gc.ca/census-recensement/2016/dp-pd/dt-td/Rp-eng.cfm?TABID=4&LANG=E&A=R&APATH=3&DETAIL=0&DIM=0&FL=A&FREE=0&GC=01&GL=-1&GID=1324838&GK=1&GRP=1&O=D&PID=110453&PRID=10&PTYPE=109445&S=0&SHOWALL=0&SUB=0&Temporal=2017&THEME=123&VID=0&VNAMEE=&VNAMEF=&D1=0&D2=0&D3=0&D4=0&D5=0&D6=0

## Model

TODO: Set up a model that works.


## FAQ

- How can I learn more about MRP? Some notes about MRP with worked examples and supporting literature are available here: https://www.tellingstorieswithdata.com/mrp.html.
- Why are you not releasing the real data? We do not want there to be any potential concern that the CES is affecting the election in any way. 
- How can I complicate the model? One way is to consider different functional specifications. Another way is to add additional layers to the model, for instance finding extra information about each riding (hint: maybe past vote!) and adding that to your model.
- Can I work as part of a team? Yes, that is recommended.

## Contact

For any questions or comments, please contact Rohan Alexander: rohan.alexander@utoronto.ca.

