---
title: "History of the data sciences"
description: |
  The data sciences have a long and robust history.
output:
  distill::distill_article:
    toc: true
    toc_depth: 3  
---

## Preamble 

### Overview



### FAQ





### Textbooks

- Stigler, S, 1986, *The History of Statistics: The Measurement of Uncertainty before 1900*, Harvard University Press.
- Friendly, M, and Wainer, H, 2021, *A History of Data Visualization and Graphic Communication*, Harvard University Press.


## Content

### Week 1

Astronomical foundations

- Content:
  - Stephen E. Fienberg, 1992, 'A Brief History of Statistics in Three and One-Half Chapters: A Review Essay', *Statistical Science*.
  - M. G. Kendall, 1960, 'Studies in the History of Probability and Statistics. Where Shall the History of Statistics Begin?', *Biometrika*.


### Week 2

Astronomical foundations, cont.

- Content:
  - Stigler, Chapter 3: Inverse Probability
  - Stigler, Chapter 4: The Gauss-Laplace Synthesis

### Week 3

Social sciences

- Content: 
  - Stigler, Chapter 5: Quetelet's Two Attempts
  - Stigler, Chapter 6: Attempts to Revive the Binomial
  

### Week 4

Heredity

- Content: 
  - Stigler, Chapter 7: Psychophysics as a Counterpoint
  - Stigler, Chapter 8: Galton

### Week 5

Heredity, cont.

- Content: 
  - Stigler, Chapter 9: Edgeworth
  - Stigler, Chapter 10: Pearson and Yule
  - David Freedman, 1999, 'From association to causation: some remarks on the history of statistics', *Journal de la société française de statistique.

### Week 6

Data visualization

- Content: 
  - Friendly and Wainer, Ch 1, In the Beginning
  - Friendly and Wainer, Ch 2, The First Graph Got It Right
  - Friendly and Wainer, Ch 3, The Birth of Data
  - Friendly and Wainer, Ch 4, Vital Statistics
  - Friendly and Wainer, Ch 5, William Playfair

### Week 7

Data visualization, cont.

- Content: 
  - Friendly and Wainer, Ch 6, Scatterplot
  - Friendly and Wainer, Ch 7, Golden age
  - Friendly and Wainer, Ch 8, Escaping Flatland
  - Friendly and Wainer, Ch 9, Time and Space
  - Friendly and Wainer, Ch 10, Graphs as Poetry
  

### Week 8

The rise of computers

- Content: 
  - William D. Nordhaus, 'An Economic History of Computing'
  - Stephen M. Stigler, 1996, 'The History of Statistics in 1933', *Statistical Science*

### Week 9

The rise of Bayesian methods

- Content: 
  - Stephen E. Fienberg, 2006, 'When Did Bayesian Inference Become "Bayesian"?', *Bayesian Analysis*.
  - Thomas Hoskyns Leonard, 2014, 'A personal history of Bayesian statistics', *WIREs Computational Statistics*.

### Week 10

Whither statistics? The rise of data science

- Content: 
  - Leo Breiman, 2001, 'Statistical Modeling: The Two Cultures', *Statistical Sciences*.
  - David J. Hand, 2015, 'Statistics and computing: the genesis of data science', *Statistics and Computing*.

### Week 11

Overlooked contributors

- Content: 
  - Margo Anderson, 1992, 'The History of Women and the History of Statistics', *Journal of Women's History*


### Week 12

Reckoning with the past

- Content: 
  - How to consider our history?
  
  

## Assessment

### Summary


| Item 								| Weight (%) | Due date |
| ------------- | -------------:| -----:|
| Weekly quiz 						| 10 		 | Weekly before the lecture |
| Tutorial 						| 10 		 | Weekly before the lecture |
| Professional conduct			| 1 		 | Anytime during the teaching term |
| Paper 1 							| 25 		 | End of Week 3 |
| Paper 2 							| 25 		 | End of Week 6 |
| Paper 3 							| 25 		 | End of Week 9 |
| Final Paper (initial submission)  | 1 		 | End of Week 12 |
| Final Paper (peer review) 		| 3 		 | Three days after that |
| Final Paper 						| 25 		 | Ten days after that |



### Weekly quizzes

- Due date: Weekly before the lecture.
- Weight: 10 per cent (only best eight out of twelve count.)
- Task: Please complete a weekly quiz in Quercus.
- Questions: The questions that form the quiz are drawn from those in the Quiz sections of *Telling Stories with Data*.


### Tutorial

- Due date: Weekly before the lecture.
- Weight: 10 per cent (only best five out of twelve count.)
- Task: Please complete a tutorial question and submit it via Quercus.
- Questions: Tutorial questions are drawn from those in the Tutorials sections of *Telling Stories with Data*.


### Professional conduct

- Due date: Anytime during the teaching term.
- Weight: 1 per cent
- Task: We (optionally) use Slack to interact in this class. At some point during the teaching term, please use Slack to answer another student's question or otherwise similarly be generally helpful in a professional manner. When you do that, please share the comment into the 'Professional conduct' channel and @ me (hover on the message, click share message, type in the channel 'profession_conduct', add a message that @'s me, and click 'share'). You'll get the full mark just for one helpful interaction. (If you are opting out of using Slack - which is entirely fine - then instead, at some point in the term send me an email with a link that is relevant to the course materials and that I should add to the course notes. Please be clear that this is your 'professional conduct' submission by stating that in the subject line.)


### Paper #1

- Due date: End of Week 3.
- Weight: 25 per cent (for Papers #1-#3 the best two of three count).
- Task: ['Mandatory minimums'](https://www.tellingstorieswithdata.com/papers.html#mandatory-minimums)



### Paper #2

- Due date: End of Week 6.
- Weight: 25 per cent (for Papers #1-#3 the best two of three counts).


### Paper #3

- Due date: End of Week 9.
- Weight: 25 per cent (for Papers #1-#3 the best two of three counts).



### Final Paper

- Due dates: 
  - Initial submission: End of Week 12.
  - Peer review: Three days after that.
  - Final Paper: Ten days after that.
- Weight: 29 per cent (4 per cent of this is for initial submission and peer review conducted a week before).
  - Initial submission: 1 per cent
  - Peer review: 3 per cent
  - Final Paper: 25 per cent



