---
title: "Toronto Data Lab"
---

The Toronto Data Lab exists to:

1. conduct research at the intersection of information and statistical sciences; 
2. bring together research from various academic disciplines and industry; and
3. provide high-quality training opportunities for students.

We run the Toronto Data Workshop - sign up [here](https://forms.gle/sXbEixoa1iJR4Q7A8).

## Director/PI

- Rohan Alexander

## Faculty affiliates

- Kelly Lyons: [Professor Lyons](http://individual.utoronto.ca/klyons/) provides crucial leadership and guidance for the Toronto Data Lab. She is an expert in information and computer science, in particular, the field of service science. Her experience in both academia and industry mean that she is as comfortable writing code as she is writing values statements.

## Graduate students

Graduate students are equal partners, have considerable autonomy, and are given co-authorship. Graduate students take ownership of their project and contribute critically to its success. All of the following are highly recommended.

- **A Mahfouz**, July 2020 - *current*
    - `dlarXiv`: This R package makes it easier to responsibly download papers from arXiv.
    - 'Discussions of bias in AI/ML research': In this paper we gather a sample of recent AI/ML research and use natural language processing to understand the extent to which bias, in an ethical rather than statistical sense, is considered.
    - 'Communicating geographically-based Bayesian models': In this paper we introduce a method to communicate the geographic results of Bayesian models. 
- **Diego Mamanche Castellanos**, August 2020 - *current*
    - 'Understanding OCR in the context of a broader statistical workflow': In this paper we examine various optical character recognition (OCR) options, and how their outputs affect subsequent statistical analysis.
- **Hidaya Ismail**, July 2020 - *current*
    - 'Bias in TikTok': We gather and examine data from TikTok to understand the role of bias.
- **Ke-Li Chiu**, July 2020 - *current*
    - 'Consistency scores in text data': In this paper we introduce a process to clean the text extracted from PDFs using various methods from natural language processing.
- **Paul Hodgetts**, July 2020 - *current*
    - `cesR`: This R package makes it easier to gather and use the Canadian Election Study surveys from 1965 through to 2019.

If you are a U of T student and would like to join the lab then we advertise for positions from time to time and you should keep an eye out for those. Impressive applicants have GitHub repos that show off their best work.


