---
title: "The Course"
description: |
  This is a course on the fundamentals of data science.
output:
  distill::distill_article:
    toc: true
    toc_depth: 3  
---

## Preamble 

### Overview

The course will be an enormous amount of work and cause you a large amount of stress. This is unfortunate, but there's little way around it. All I can tell you is that having done this course, it'll be easier in the future.

The purpose of this course is to develop students who appreciate, and can iterate on, the fundamentals of data science.

 
This course will require students to:

- actively read and consider a large amount of literature;
- actively learn the statistical programming language R and apply it to real-world conditions;
- gather, clean, and prepare their own datasets; and
- develop killer statistics skills, including the critical aspect of being able to communicate.

Essentially this course provides students with everything that they need to know to be able to do the most exciting thing in the world: use data to tell convincing stories.


### FAQ

- Can I audit this course? Sure, but it's pointless, because the only way to learn this stuff is to do the work.
- Can I attend lectures? Sure, but it's just me running through code.
- What is a tutorial? You write a paper. Then you send it to your tutor. The next day you have a meeting 'tutorial' where you discuss it with them.
- Why is there so much assessment? The only way to learn is to actually do the work, and students only do the work when they are assessed. It's unfortunate, but there's no way around it.


### Pre-requisites

None.

### Textbook

Alexander, 2022, *Telling Stories with Data*, CRC Press, https://www.tellingstorieswithdata.com.

### Acknowledgements

Thank you to Monica Alexander.




## Content

### Week 1

'Drinking from a fire hose'.

- Content:
  - *Telling Stories with Data*, Chapter 1: [Drinking from a fire hose](https://www.tellingstorieswithdata.com/drinking-from-a-fire-hose.html)
  - *Telling Stories with Data*, Chapter 2: [R Essentials](https://www.tellingstorieswithdata.com/r-essentials.html).


### Week 2

'Science-ing'.

- Content: 
  - *Telling Stories with Data*, Chapter 4: [Workflow](https://www.tellingstorieswithdata.com/workflow.html), 
  - *Telling Stories with Data*, Chapter 5: [Writing](https://www.tellingstorieswithdata.com/on-writing.html).


### Week 3

'Communicating'.

- Content: 
  - *Telling Stories with Data*, Chapter 6: [Static communication](https://www.tellingstorieswithdata.com/static-communication.html)
  - *Telling Stories with Data*, Chapter 7: [Interactive communication](https://www.tellingstorieswithdata.com/interactive-communication.html).



### Week 4

'Gathering data'.

- Content: 
  - *Telling Stories with Data*, Chapter 8: [Gathering data](https://www.tellingstorieswithdata.com/gather-data.html).

### Week 5

'Hunting data'.

- Content: 
  - *Telling Stories with Data*, Chapter 9: [Hunting data](https://www.tellingstorieswithdata.com/hunt-data.html).


### Week 6

'Cleaning data'.

- Content: 
  - *Telling Stories with Data*, Chapter 11: [Clean and prepare data](https://www.tellingstorieswithdata.com/cleaning-and-preparing-data.html)


### Week 7

'Store, retrieve, disseminate and protect'.

- Content: 
  - *Telling Stories with Data*, Chapter 12: [Storing and retrieving data](https://www.tellingstorieswithdata.com/storing-and-retrieving-data.html), 
  - *Telling Stories with Data*, Chapter 13: [Disseminating and protecting data](https://www.tellingstorieswithdata.com/disseminating-and-protecting-data.html)


### Week 8

'Whoops, I forgot EDA'.

- Content: 
  - *Telling Stories with Data*, Chapter 14: [Exploratory Data Analysis](https://www.tellingstorieswithdata.com/exploratory-data-analysis.html).



### Week 9

'IJALM - It's Just A Linear Model'.

- Content: 
  - *Telling Stories with Data*, Chapter 15: [It's just a linear model](https://www.tellingstorieswithdata.com/ijalm.html)



### Week 10

'Such a shame they'll never meet'.

- Content: 
  - *Telling Stories with Data*, Chapter 16: [Causality from observational data](https://www.tellingstorieswithdata.com/causality.html)



### Week 11

'Multilevel regression with post-stratification'.

- Content: 
  - *Telling Stories with Data*, Chapter 17: [MRP](https://www.tellingstorieswithdata.com/mrp.html)

### Week 12

'Lorem ipsum'.

- Content: 
  - *Telling Stories with Data*, Chapter 18: [Text-as-data](https://www.tellingstorieswithdata.com/text-as-data.html).




## Assessment

### Summary


| Item 								| Weight (%) | Due date |
| ------------- | -------------:| -----:|
| Weekly quiz 						| 20 		 | Weekly before the lecture |
| Professional conduct			| 1 		 | Anytime during the teaching term |
| Paper 1 							| 25 		 | End of Week 3 |
| Paper 2 							| 25 		 | End of Week 6 |
| Paper 3 							| 25 		 | End of Week 9 |
| Final Paper (initial submission)  | 1 		 | End of Week 12 |
| Final Paper (peer review) 		| 3 		 | Three days after that |
| Final Paper 						| 25 		 | Ten days after that |



### Weekly quizzes

- Due date: Weekly before the lecture.
- Weight: 20 per cent (only best eight out of twelve count.)
- Task: Please complete a weekly quiz in Quercus.
- Questions: The questions that form the quiz are drawn from those in the Quiz sections *Telling Stories with Data*.


### Professional conduct

- Due date: Anytime during the teaching term.
- Weight: 1 per cent
- Task: We (optionally) use Slack to interact in this class. At some point during the teaching term, please use Slack to answer another student's question or otherwise similarly be generally helpful in a professional manner. When you do that, please share the comment into the 'Professional conduct' channel and @ me (hover on the message, click share message, type in the channel 'profession_conduct', add a message that @'s me, and click 'share'). You'll get the full mark just for one helpful interaction. (If you are opting out of using Slack - which is entirely fine - then instead, at some point in the term send me an email with a link that is relevant to the course materials and that I should add to the course notes. Please be clear that this is your 'professional conduct' submission by stating that in the subject line.)


### Paper #1

- Due date: End of Week 3.
- Weight: 25 per cent (for Papers #1-#3 the best two of three count).
- Task: ['Mandatory minimums'](https://www.tellingstorieswithdata.com/papers.html#mandatory-minimums)



### Paper #2

- Due date: End of Week 6.
- Weight: 25 per cent (for Papers #1-#3 the best two of three counts).
- Task: ['These numbers mean dial it up'](https://www.tellingstorieswithdata.com/papers.html#these-numbers-mean-dial-it-up)


### Paper #3

- Due date: End of Week 9.
- Weight: 25 per cent (for Papers #1-#3 the best two of three counts).
- Task: ['The Short List'](https://www.tellingstorieswithdata.com/papers.html#the-short-list).



### Final Paper

- Due dates: 
  - Initial submission: End of Week 12.
  - Peer review: Three days after that.
  - Final Paper: Ten days after that.
- Weight: 29 per cent (4 per cent of this is for initial submission and peer review conducted a week before).
  - Initial submission: 1 per cent
  - Peer review: 3 per cent
  - Final Paper: 25 per cent
- Task: ['Two Cathedrals'](https://www.tellingstorieswithdata.com/papers.html#two-cathedrals)


